# coding: utf-8

"""
    API contract for financial accelerator extension points in WSO2 IS and APIM

    This API defines the REST API contract for services that implements logic to extend the Open Data accelerator flow.

    The version of the OpenAPI document: v1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ClientProcessData(BaseModel):
    """
    Defines the context data related to the client registration.
    """ # noqa: E501
    client_data: Optional[Dict[str, Any]] = Field(default=None, description="Client Registration Data. Mandatory for pre-process-client-creation and pre-process-client-update.", alias="clientData")
    software_statement: Optional[Dict[str, Any]] = Field(default=None, description="Parameters of the decoded SSA. Mandatory for pre-process-client-creation, pre-process-client-update and pre-process-client-retrieval.", alias="softwareStatement")
    existing_client_data: Optional[Dict[str, Any]] = Field(default=None, description="properties of the existing client application. Mandatory for pre-process-client-update.", alias="existingClientData")
    __properties: ClassVar[List[str]] = ["clientData", "softwareStatement", "existingClientData"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ClientProcessData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ClientProcessData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientData": obj.get("clientData"),
            "softwareStatement": obj.get("softwareStatement"),
            "existingClientData": obj.get("existingClientData")
        })
        return _obj


