/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ErrorResponse;
import org.openapitools.model.GetConsentContentRequestBody;
import org.openapitools.model.Response200ForGetConsentContent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-11T10:28:00.000000000Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
@Validated
@Tag(name = "Consent", description = "APIs for consent flow extensions")
public interface GetConsentContentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_CONSENT_CONTENT_POST = "/get-consent-content";
    /**
     * POST /get-consent-content : Get consent content with ACTV or RJCT status as per Berlin Group specification
     * This endpoint responds to GET Consent-Content Requests with HTTP Status Code 200 (OK) 
     * containing ACTV (Active) or RJCT (Rejected) status information. This complies with 
     * Berlin Group PSD2 Account Information Consent Flow diagram requirements.
     * 
     * The ASPSP returns consent status information including:
     * - ACTV: Consent is active and valid
     * - RJCT: Consent has been rejected
     *
     * @param getConsentContentRequestBody  (required)
     * @return Ok - Returns consent content with ACTV or RJCT status (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "getConsentContentPost",
        summary = "Get consent content with ACTV or RJCT status as per Berlin Group specification",
        description = "This endpoint responds to GET Consent-Content Requests with HTTP Status Code 200 (OK) containing ACTV (Active) or RJCT (Rejected) status information. This complies with Berlin Group PSD2 Account Information Consent Flow diagram requirements.  The ASPSP returns consent status information including: - ACTV: Consent is active and valid - RJCT: Consent has been rejected ",
        tags = { "Consent" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok - Returns consent content with ACTV or RJCT status", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForGetConsentContent.class), examples = {
                    @ExampleObject(name = "ConsentACTV", summary = "Consent with ACTV Status", value = "{ \"responseId\": \"Ec1wMjmiG8\", \"status\": \"SUCCESS\", \"data\": { \"consentStatus\": \"ACTV\", \"consentId\": \"consent-12345\", \"statusDescription\": \"Consent is active\", \"consentDetails\": { \"validUntil\": \"2026-12-31T23:59:59Z\", \"permissions\": [ \"ReadAccountsBasic\", \"ReadBalances\" ] } } }"),
                    @ExampleObject(name = "ConsentRJCT", summary = "Consent with RJCT Status", value = "{ \"responseId\": \"Ec1wMjmiG8\", \"status\": \"SUCCESS\", \"data\": { \"consentStatus\": \"RJCT\", \"consentId\": \"consent-12345\", \"statusDescription\": \"Consent has been rejected\", \"rejectionReason\": \"User denied consent\" } }")
                })
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GetConsentContentApi.PATH_GET_CONSENT_CONTENT_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForGetConsentContent> getConsentContentPost(
        @Parameter(name = "GetConsentContentRequestBody", description = "", required = true) @Valid @RequestBody GetConsentContentRequestBody getConsentContentRequestBody
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"responseId\" : \"Ec1wMjmiG8\", \"status\" : \"SUCCESS\", \"data\" : { \"consentStatus\" : \"ACTV\", \"consentId\" : \"consent-12345\", \"statusDescription\" : \"Consent is active\", \"consentDetails\" : { \"validUntil\" : \"2026-12-31T23:59:59Z\", \"permissions\" : [ \"ReadAccountsBasic\", \"ReadBalances\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
