/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ConsentContentRequestBody;
import org.openapitools.model.ErrorResponse;
import org.openapitools.model.Response200ForConsentContent;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-10T04:52:48Z[Etc/UTC]", comments = "Generator version: 7.2.0")
@Validated
@Tag(name = "Consent", description = "APIs for consent flow extensions")
public interface GetConsentContentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_CONSENT_CONTENT_POST = "/get-consent-content";
    /**
     * POST /get-consent-content : retrieve consent content after TPP redirection
     *
     * @param consentContentRequestBody  (required)
     * @return Ok (status code 200)
     *         or Bad Request (status code 400)
     *         or Server Error (status code 500)
     */
    @Operation(
        operationId = "getConsentContentPost",
        summary = "retrieve consent content after TPP redirection",
        tags = { "Consent" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response200ForConsentContent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OAuth2"),
            @SecurityRequirement(name = "BasicAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GetConsentContentApi.PATH_GET_CONSENT_CONTENT_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Response200ForConsentContent> getConsentContentPost(
        @Parameter(name = "ConsentContentRequestBody", description = "", required = true) @Valid @RequestBody ConsentContentRequestBody consentContentRequestBody
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : { \"consentId\" : \"consent-uuid-12345\", \"consentResource\" : { \"updatedTime\" : 6, \"validityTime\" : 5, \"clientId\" : \"clientId\", \"createdTime\" : 0, \"receipt\" : \"{}\", \"recurringIndicator\" : true, \"attributes\" : \"{}\", \"id\" : \"id\", \"type\" : \"type\", \"status\" : \"status\", \"frequency\" : 1 } }, \"responseId\" : \"responseId\", \"status\" : \"SUCCESS\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
